name: tagpr

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  tagpr:
    runs-on: ubuntu-latest
    outputs:
      # Make tagpr execution results available to other jobs
      tag-name: ${{ steps.run-tagpr.outputs.tag-name }}
      tag-created: ${{ steps.run-tagpr.outputs.tag-created }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Run tagpr
        id: run-tagpr
        uses: Songmu/tagpr@0a9ef64ad975dce30c6fb2547f9e1ac89b5f1f76 # v1.11.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
